import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Upload, Play, Check, X, Bot, FileText, ShieldCheck, Download, RefreshCw, ExternalLink } from "lucide-react";
import api from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";

const emptyExportIdentity={pan:"",first_name:"",middle_name:"",surname:"",date_of_birth:"",email:"",mobile:"",address:{ResidenceNo:"",ResidenceName:"",CityOrTownOrDistrict:"",StateCode:"",PinCode:""},verification_place:"",verification_capacity:"S"};

export default function CaseWorkspaceV3(){
  const{id}=useParams();const navigate=useNavigate();
  const[caseData,setCaseData]=useState(null);const[documents,setDocuments]=useState([]);const[candidates,setCandidates]=useState([]);const[facts,setFacts]=useState([]);const[latest,setLatest]=useState(null);const[missing,setMissing]=useState([]);const[reconciliation,setReconciliation]=useState([]);const[exportsList,setExportsList]=useState([]);const[audit,setAudit]=useState([]);const[selectedDocument,setSelectedDocument]=useState(null);const[evidence,setEvidence]=useState([]);const[assistantText,setAssistantText]=useState("");const[assistantResult,setAssistantResult]=useState(null);const[identity,setIdentity]=useState(emptyExportIdentity);const[error,setError]=useState("");const[busy,setBusy]=useState("");
  const computation=latest?.result||caseData?.latest_computation||null;
  const load=async()=>{setError("");try{const requests=[api.get(`/cases/${id}`),api.get(`/cases/${id}/documents`),api.get(`/cases/${id}/candidate-facts`),api.get(`/cases/${id}/facts`),api.get(`/cases/${id}/missing-items`),api.get(`/cases/${id}/reconciliation`),api.get(`/cases/${id}/exports`),api.get(`/cases/${id}/audit-events`)];const[a,b,c,d,e,f,g,h]=await Promise.all(requests);setCaseData(a.data);setDocuments(b.data);setCandidates(c.data);setFacts(d.data);setMissing(e.data);setReconciliation(f.data);setExportsList(g.data);setAudit(h.data);try{const latestResponse=await api.get(`/cases/${id}/computations/latest`);setLatest(latestResponse.data);}catch(err){if(err.response?.status!==404)throw err;setLatest(null);}}catch(err){setError(err.response?.data?.detail||err.message)}};
  useEffect(()=>{void load();},[id]);
  const pendingCount=useMemo(()=>candidates.filter(c=>["PENDING_REVIEW","CONFLICTING","VALIDATED","EXTRACTED"].includes(c.status)).length,[candidates]);
  const act=async(label,fn)=>{setBusy(label);setError("");try{await fn();await load();}catch(err){setError(err.response?.data?.detail||err.message)}finally{setBusy("")}};
  const upload=async(event)=>{const file=event.target.files?.[0];if(!file)return;await act("upload",async()=>{const form=new FormData();form.append("file",file);const{data}=await api.post(`/cases/${id}/documents`,form,{headers:{"Content-Type":"multipart/form-data"}});await api.post(`/documents/${data.id}/extract`);});event.target.value="";};
  const review=(candidate,decision)=>act(`candidate-${candidate.id}`,()=>api.post(`/candidate-facts/${candidate.id}/review`,{decision,justification:`${decision} after reviewing the source evidence and client context in the CA workspace.`}));
  const compute=()=>act("compute",()=>api.post(`/cases/${id}/computations`,{selected_regime:caseData?.selected_regime||"NEW"}));
  const approveComputation=()=>{if(!latest?.id)return;return act("approve-computation",()=>api.post(`/computations/${latest.id}/review`,{decision:"APPROVE",justification:"Final deterministic computation, evidence links, blockers and tax positions reviewed by the authorised CA reviewer."}));};
  const ask=async()=>{if(!assistantText.trim())return;setBusy("assistant");try{const{data}=await api.post(`/cases/${id}/assistant/tools`,{name:"search_tax_law",arguments:{query:assistantText,tax_period:caseData?.assessment_year||"AY 2026-27",act_namespace:caseData?.act_namespace||"ITA_1961"},idempotency_key:`ui-${Date.now()}`});setAssistantResult(data);}catch(err){setError(err.response?.data?.detail||err.message)}finally{setBusy("")}};
  const showDocument=async(document)=>{setSelectedDocument(document);const{data}=await api.get(`/documents/${document.id}/evidence`);setEvidence(data);};
  const openDocument=async()=>{if(!selectedDocument)return;const{data}=await api.get(`/documents/${selectedDocument.id}/content`,{responseType:"blob"});const url=URL.createObjectURL(data);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000);};
  const resolveMissing=item=>act(`missing-${item.id}`,()=>api.post(`/missing-items/${item.id}/resolve`));
  const resolveReconciliation=item=>act(`reconcile-${item.id}`,()=>api.post(`/reconciliation/${item.id}/resolve`,{accepted_fact_id:item.accepted_fact_id,status:"RESOLVED",resolution_note:"Difference reviewed against source evidence; the currently accepted canonical fact remains the approved tax input."}));
  const approveExport=item=>act(`approve-export-${item.id}`,()=>api.post(`/exports/${item.id}/review`,{decision:"APPROVE",justification:"Pinned schema validation, configured utility validation and final computation were reviewed by the authorised CA reviewer."}));
  const createExport=()=>{if(!latest?.id)return;return act("export",()=>api.post(`/cases/${id}/exports`,{computation_run_id:latest.id,form_code:computation?.form_eligibility?.recommended_form||"ITR_1",identity,intermediary_city:identity.verification_place||"Mumbai",schema_version:"V1.1"}));};
  if(!caseData)return <div className="p-10">Loading case… {error&&String(error)}</div>;
  return <div className="h-screen bg-slate-100 flex flex-col"><header className="bg-white border-b px-5 py-3 flex items-center justify-between"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" onClick={()=>navigate("/dashboard")}><ArrowLeft className="h-5 w-5"/></Button><div><h1 className="font-display text-xl">{caseData.client_name}</h1><p className="text-xs text-slate-500">{caseData.tax_period} · {caseData.status} · {caseData.rule_release_id}</p></div></div><div className="flex items-center gap-2"><Button variant="outline" onClick={load}><RefreshCw className="h-4 w-4 mr-2"/>Refresh</Button><label className="cursor-pointer"><input type="file" className="hidden" onChange={upload}/><span className="inline-flex h-10 items-center rounded-md bg-slate-900 px-4 text-sm text-white"><Upload className="h-4 w-4 mr-2"/>{busy==="upload"?"Processing…":"Upload document"}</span></label></div></header>
    {error&&<div className="bg-red-50 border-b border-red-200 px-5 py-2 text-sm text-red-700">{typeof error==="string"?error:JSON.stringify(error)}</div>}
    <div className="flex-1 grid xl:grid-cols-[40%_60%] min-h-0">
      <section className="border-r bg-white p-4 overflow-auto"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Bot className="h-5 w-5"/>Controlled tax assistant</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-slate-600">The assistant searches approved official sources and reads stored traces. It cannot approve facts, change rules or file a return.</p><div className="flex gap-2"><Input value={assistantText} onChange={e=>setAssistantText(e.target.value)} placeholder="Ask about an approved tax provision…" onKeyDown={e=>{if(e.key==="Enter")void ask();}}/><Button onClick={ask} disabled={busy==="assistant"}>Ask</Button></div>{assistantResult&&<pre className="text-xs whitespace-pre-wrap bg-slate-50 p-3 rounded max-h-72 overflow-auto">{JSON.stringify(assistantResult,null,2)}</pre>}</CardContent></Card>
      <Card className="mt-4"><CardHeader><CardTitle className="text-lg">Documents</CardTitle></CardHeader><CardContent className="space-y-2">{documents.map(document=><button className={`w-full border rounded p-3 text-left ${selectedDocument?.id===document.id?"border-slate-900 bg-slate-50":""}`} key={document.id} onClick={()=>showDocument(document)}><div className="font-medium flex gap-2"><FileText className="h-4 w-4"/>{document.filename}</div><div className="text-xs text-slate-500">{document.document_type} · {document.state}</div></button>)}{!documents.length&&<p className="text-sm text-slate-500">Upload Form 16, AIS/TIS, 26AS, bank or broker files.</p>}{selectedDocument&&<div className="pt-3 border-t"><Button variant="outline" size="sm" onClick={openDocument}><ExternalLink className="h-4 w-4 mr-2"/>Open original</Button><div className="mt-3 space-y-2 max-h-64 overflow-auto">{evidence.map(item=><div key={item.id} className="rounded bg-slate-50 p-2 text-xs"><div className="font-medium">{item.field_code}</div><div>Page {(item.page_index??0)+1} · {item.extraction_method} · {item.confidence||"review"}</div><div className="mt-1 text-slate-600">{item.original_text||JSON.stringify(item.value)}</div></div>)}</div></div>}</CardContent></Card></section>
      <section className="p-4 overflow-auto"><Tabs defaultValue="computation"><TabsList className="flex flex-wrap h-auto"><TabsTrigger value="computation">Computation</TabsTrigger><TabsTrigger value="review">Fact review ({pendingCount})</TabsTrigger><TabsTrigger value="evidence">Approved facts</TabsTrigger><TabsTrigger value="issues">Issues ({missing.filter(x=>x.status==="OPEN").length})</TabsTrigger><TabsTrigger value="reconciliation">Reconciliation ({reconciliation.length})</TabsTrigger><TabsTrigger value="export">Export</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList>
        <TabsContent value="computation"><div className="flex justify-end gap-2 mb-3"><Button onClick={compute} disabled={busy==="compute"}><Play className="h-4 w-4 mr-2"/>Run deterministic computation</Button>{latest&&<Button variant="outline" onClick={approveComputation} disabled={latest.approved_by||computation?.status!=="COMPLETE"}><ShieldCheck className="h-4 w-4 mr-2"/>{latest.approved_by?"Approved":"Approve final"}</Button>}</div>{computation?<Computation result={computation} latest={latest}/>:<Card><CardContent className="p-10 text-center text-slate-500">Approve source facts, then run the deterministic computation.</CardContent></Card>}</TabsContent>
        <TabsContent value="review"><div className="space-y-3">{candidates.map(candidate=><Card key={candidate.id}><CardContent className="p-4 flex justify-between gap-4"><div><div className="font-medium">{candidate.field_code}</div><pre className="text-xs mt-2 whitespace-pre-wrap">{JSON.stringify(candidate.value,null,2)}</pre><div className="text-xs text-slate-500 mt-2">{candidate.status} · evidence {candidate.evidence_claim_ids.length}</div></div>{["PENDING_REVIEW","CONFLICTING","VALIDATED","EXTRACTED"].includes(candidate.status)&&<div className="flex gap-2"><Button size="sm" onClick={()=>review(candidate,"ACCEPT")}><Check className="h-4 w-4"/></Button><Button size="sm" variant="destructive" onClick={()=>review(candidate,"REJECT")}><X className="h-4 w-4"/></Button></div>}</CardContent></Card>)}</div></TabsContent>
        <TabsContent value="evidence"><div className="space-y-2">{facts.map(fact=><Card key={fact.id}><CardContent className="p-4"><div className="font-medium">{fact.field_code} · {fact.entity_key}</div><pre className="text-xs mt-2 whitespace-pre-wrap">{JSON.stringify(fact.value,null,2)}</pre><div className="text-xs text-slate-500">Version {fact.version}</div></CardContent></Card>)}</div></TabsContent>
        <TabsContent value="issues"><div className="space-y-3">{missing.map(item=><Card key={item.id} className={item.blocking?"border-red-300":""}><CardContent className="p-4 flex justify-between gap-4"><div><div className="font-medium">{item.title}</div><div className="text-sm text-slate-600 mt-1">{item.reason}</div><div className="text-xs mt-2">{item.priority} · {item.status} · {item.blocking?"Blocks finalisation":"Review required"}</div></div>{item.status==="OPEN"&&<Button variant="outline" size="sm" onClick={()=>resolveMissing(item)}>Resolve</Button>}</CardContent></Card>)}</div></TabsContent>
        <TabsContent value="reconciliation"><div className="space-y-3">{reconciliation.map(item=><Card key={item.id}><CardContent className="p-4"><div className="flex justify-between"><div className="font-medium">{item.category} · {item.entity_key}</div><div className={item.status==="MATCHED"?"text-green-700":"text-amber-700"}>{item.status}</div></div><pre className="text-xs mt-3 bg-slate-50 p-3 overflow-auto">{JSON.stringify(item.source_values,null,2)}</pre>{item.difference_amount&&<div className="text-sm mt-2">Difference: ₹{item.difference_amount}</div>}{item.status!=="RESOLVED"&&<Button variant="outline" size="sm" className="mt-3" onClick={()=>resolveReconciliation(item)}>Resolve after evidence review</Button>}</CardContent></Card>)}</div></TabsContent>
        <TabsContent value="export"><ExportPanel latest={latest} computation={computation} identity={identity} setIdentity={setIdentity} createExport={createExport} approveExport={approveExport} exportsList={exportsList}/></TabsContent>
        <TabsContent value="history"><div className="space-y-2">{audit.map(event=><Card key={event.id}><CardContent className="p-3"><div className="font-medium">{event.action}</div><div className="text-xs text-slate-500">{event.actor_role} · {new Date(event.occurred_at).toLocaleString()}</div><div className="text-xs mt-1">{event.entity_type} {event.entity_id||""}</div></CardContent></Card>)}</div></TabsContent>
      </Tabs></section>
    </div></div>;
}

function Computation({result,latest}){const selected=result.selected_result||{};return <div className="grid md:grid-cols-2 gap-4"><Card><CardHeader><CardTitle>Selected regime: {result.selected_regime}</CardTitle></CardHeader><CardContent className="space-y-2">{[["Gross total income",selected.gross_total_income],["Deductions",selected.deductions],["Total income",selected.total_income],["Tax liability",selected.total_tax_liability],["Tax paid",selected.tax_paid],["Payable",selected.payable],["Refund",selected.refund]].map(([label,value])=><div className="flex justify-between border-b py-2" key={label}><span>{label}</span><strong>₹{value||"0.00"}</strong></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Trace and controls</CardTitle></CardHeader><CardContent><div className="text-sm">Status: <b>{result.status}</b></div><div className="text-sm mt-2">Approval: <b>{latest?.approved_by?"CA approved":"Pending"}</b></div><div className="text-sm mt-2">Recommended regime: <b>{result.recommended_regime}</b></div><div className="text-sm mt-2">Recommended form: <b>{result.form_eligibility?.recommended_form||"Review required"}</b></div><div className="text-xs mt-4 break-all">Result hash: {result.result_hash}</div><div className="text-xs mt-2">Calculation lines: {result.calculation_lines?.length||0}</div></CardContent></Card></div>}

function ExportPanel({latest,computation,identity,setIdentity,createExport,approveExport,exportsList}){const set=(key,value)=>setIdentity(current=>({...current,[key]:value}));return <div className="grid lg:grid-cols-2 gap-4"><Card><CardHeader><CardTitle>Official export gate</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-slate-600">An export is created only after final computation approval, pinned official schema validation and configured utility validation.</p><div className="grid grid-cols-2 gap-2"><Input placeholder="PAN" value={identity.pan} onChange={e=>set("pan",e.target.value.toUpperCase())}/><Input placeholder="First name" value={identity.first_name} onChange={e=>set("first_name",e.target.value)}/><Input placeholder="Surname" value={identity.surname} onChange={e=>set("surname",e.target.value)}/><Input type="date" value={identity.date_of_birth} onChange={e=>set("date_of_birth",e.target.value)}/><Input placeholder="Email" value={identity.email} onChange={e=>set("email",e.target.value)}/><Input placeholder="Mobile" value={identity.mobile} onChange={e=>set("mobile",e.target.value)}/><Input placeholder="Verification place" value={identity.verification_place} onChange={e=>set("verification_place",e.target.value)}/></div><Button onClick={createExport} disabled={!latest?.approved_by||computation?.status!=="COMPLETE"}><Download className="h-4 w-4 mr-2"/>Build validated export</Button></CardContent></Card><Card><CardHeader><CardTitle>Export snapshots</CardTitle></CardHeader><CardContent className="space-y-2">{exportsList.map(item=><div className="border rounded p-3" key={item.id}><div className="font-medium">{item.form_code} · {item.status}</div><div className="text-xs text-slate-500">Schema {item.schema_version} · {item.validation_version}</div><div className="text-xs break-all mt-1">{item.snapshot_hash}</div>{item.status==="READY_FOR_CA_REVIEW"&&<Button size="sm" className="mt-2" onClick={()=>approveExport(item)}>Approve export</Button>}{item.status==="READY_FOR_UTILITY_VALIDATION"&&<div className="text-xs text-amber-700 mt-2">Run the configured official utility validator before CA approval.</div>}{item.status==="APPROVED"&&<button className="text-sm underline mt-2 inline-block" onClick={async()=>{const{data}=await api.get(`/exports/${item.id}/download`,{responseType:"blob"});const url=URL.createObjectURL(data);const link=document.createElement("a");link.href=url;link.download=`${item.form_code}.json`;link.click();URL.revokeObjectURL(url);}}>Download</button>}</div>)}{!exportsList.length&&<p className="text-sm text-slate-500">No immutable export snapshots yet.</p>}</CardContent></Card></div>}
